### ISSUE TITLE
Possible bug in get_teff_obs()

### ISSUE THREAD

**Issue by copernican** [jtimonen/lgpr#22]
**Describe the bug**
`get_teff_obs()` accepts the argument `group_by`, but the call to `pick_one_row_each()` uses the default value `"id"`. (While `get_teff_obs()` is not exported, it is called by functions that are, e.g., `new_x()`.)

**To Reproduce**

```r
library(lgpr)
#> Attached lgpr 1.0.12, using rstan 2.21.2.
dat <- data.frame(
  id = factor(rep(letters[1:2], each = 2)),
  age = c(16, 17, 36, 37),
  diseaseAge = c(1, 2, 4, 5)
)
lgpr:::get_teff_obs(dat)
#>  a  b 
#> 15 32
dat$subj_id <- dat$id
dat$id <- NULL
lgpr:::get_teff_obs(dat, group_by = "subj_id")
#> Error in dollar(data, fac): Variable with name 'id' not found in <data>! Found: {age, diseaseAge, subj_id}
```

**Expected behavior**
In the example above, I would expect `get_teff_obs()` to have the same return value in both cases, i.e., when `group_by` is not named `"id"`.

**Comment by jtimonen** [comment]
Thanks for the well made bug  report! This is now fixed in the latest patch (1.0.13).
