### ISSUE TITLE
data.table and tibble objects not accepted as data argument

### ISSUE THREAD

**Issue by Selbosh** [jtimonen/lgpr#25]
**Describe the bug**
Pass anything other than a native R data frame to the `data` argument of `create_model()` and an error is (eventually) thrown,
```
Error in parse_response(data, likelihood, model_formula) : 
  <data> must be a data.frame! found = data.tabledata.frame
```

**To Reproduce**

```r
library(lgpr)
dat <- data.table::data.table(x = 1:3, y = rnorm(3))
mod <- create_model(y ~ x, dat)
```

or

```r
tbl <- tibble::as_tibble(dat)
mod <- create_model(y ~ x, tbl)
```

This actually throws a different, hard-to-interpret error, I suspect due to the way `data.frame`s and `data.tables` do `d[i,j]` subset syntax differently:

```
Error in check_allowed(class(data[, j])[1], allowed) : 
  Error in data_types(data): The given value 'integer' for argument <class(data[, j])[1]> is invalid.
Allowed values are {factor, numeric}.
```

To get the first error (above), wrap something on the right-hand side in `gp()`:

```r
modgp <- create_model(y ~ gp(x), dat)
```

**Expected behavior**
Tibbles should work just like data frames, but the function `lgrp:::parse_response` essentially does a check of the form
```r
if (class(data) != 'data.frame')
  stop('Error message')
```
when it should maybe be doing something like `!inherits(data, 'data.frame')`.

On the other hand, `data.table`s work differently (and appear to cause problems with subsetting syntax in `lgpr`) so maybe it should just check the class of `data` earlier on and throw a more informative error message, or else call `as.data.frame` with a warning.

**Additional context**
Maybe the package shouldn't accept anything other than vanilla data.frames, but if so the checks/errors should be clearer.

For now the workaround for end-users is to explicitly coerce to a native data frame (i.e. `as.data.frame(data)`), before passing data to any `lgpr` functions.

**Comment by Selbosh** [comment]
Oops, looks like my minimal (non)-working example doesn't work, because the `x` variable is an integer and should be numeric. Seems a bit pedantic?

This should do the trick.
```r
df <- data.frame(x = as.numeric(1:3), y = rnorm(3))
tbl <- tibble::as_tibble(df)
dt <- data.table::as.data.table(df)
```

Minimal working example:

```r
mod_df <- create_model(y ~ x, df)
# works fine; no output to console
```

Tibbles:

```r
mod_tbl <- create_model(y ~ x, tbl)
```
```
Error in check_allowed(class(data[, j])[1], allowed) : 
  Error in data_types(data): The given value 'tbl_df' for argument <class(data[, j])[1]> is invalid.
Allowed values are {factor, numeric}.
```

data.tables:

```r
mod_dt <- create_model(y ~ x, dt)
```
```
Error in check_allowed(class(data[, j])[1], allowed) : 
  Error in data_types(data): The given value 'integer' for argument <class(data[, j])[1]> is invalid.
Allowed values are {factor, numeric}.
```

**Comment by jtimonen** [comment]
The development branch now has code which for example with

```
> df <- data.frame(x = as.numeric(1:3), y = rnorm(3))
> tbl <- tibble::as_tibble(df)
> mod_tbl <- create_model(y ~ x, tbl)
```

gives
```
Warning message:
In convert_to_data_frame(data) :
  data is not a plain data.frame, converting using as.data.frame()
```
but no error.

It has been intentional to allow only `data.frame`s with columns of type `numeric` or  `factor`. If a model formula is `y ~ x + z`, it will be interpreted differently depending on the types of `x` and `z`. Some people might have data where `integer` represents a continuous variable, others to describe discrete categories. If only `numeric` and `factor` are allowed, user needs to make sure what variables are continuous and what are categorical.

**Comment by Selbosh** [comment]
Thanks for the quick response!

I understand the desire to avoid ambiguity in `integer`-class variables that could be either discrete or continuous. However I'd respectfully point out that the *Biostatistics* paper says:

> "We have implemented _**lgpr**_ as a user-friendly R-package that can be used as a plug-in replacement for _**lme4**_."

In **lme4** (and **stats**, and **brms**, **rstanarm** etc), variables of class `integer` are not treated quite so strictly. So this is a contradiction and should probably be made clear in associated error/warning messages.

**Comment by jtimonen** [comment]
Yes it would be good to harmonize with those other packages, I will need to study them a bit. Of course all possible valid lme4 calls are not going to be valid for lgpr so that is bit of an overstatement.

**Comment by jtimonen** [comment]
Since 1.1 now, `lgp()` can be used with data.table or tibble as the `data` argument, with warning
```
Warning message:
In convert_to_data_frame(data) :
  data is not a plain data.frame, converting using as.data.frame()
```

It turned out to be difficult to allow integer-typed covariates as data, because for lgpr models like `y ~ x + z` the interpretation depends on the types of `x` and `z`, whereas such ambiguity is not a problem for *lme4* which only allows models that contain random effects. Therefore only factor and numeric remain allowed covariate types. The response variable can be integer.
